version: '3.3'
services:
    zookeeper:
        container_name: kafka_zookeeper
        image: confluentinc/cp-zookeeper:6.1.1
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 2181:2181
    kafka:
        container_name: kafka
        image: confluentinc/cp-kafka:6.1.1
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: kafka_zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    redis:
        container_name: redis
        image: redis:6.2.3
        ports:
            - 6379:6379
    database:
        container_name: postgres
        image: postgres:13.2-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: bank_voucher_int
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
